#!/bin/sh
alias t-anon='bash ~/.config/tmux/tmux-sessionizer.sh ~/Code/Work/Keva/Anonymisointi/Anonymisointipalvelu'
alias t-anondw='bash ~/.config/tmux/tmux-sessionizer.sh ~/Code/Work/Keva/Anonymisointi/AnonymisointiDW'
alias t-lvim-src='bash ~/.config/tmux/tmux-sessionizer.sh ~/Code/Personal/Forks/LunarVim'
alias t-massa='bash ~/.config/tmux/tmux-sessionizer.sh ~/Code/Work/Keva/Avaintiedot/Avaintiedot-Massatoimitus'
alias t-lvim='bash ~/.config/tmux/tmux-sessionizer.sh ~/.config/lvim'
alias t-oet-api='bash ~/.config/tmux/tmux-sessionizer.sh ~/Code/Work/Keva/OET-2.0/oet-api'
alias t-oet-ui='bash ~/.config/tmux/tmux-sessionizer.sh ~/Code/Work/Keva/OET-2.0/oet-ui'
alias t-vipa-api='bash ~/.config/tmux/tmux-sessionizer.sh ~/Code/Work/Keva/ViPa-2.0/vipa-api'
alias t-peli-api='bash ~/.config/tmux/tmux-sessionizer.sh ~/Code/Work/Keva/Tyokykypolkuja-oppimispeli/Tyokykypolkuja.WebAPI'
alias t-peli-ui='bash ~/.config/tmux/tmux-sessionizer.sh ~/Code/Work/Keva/Tyokykypolkuja-oppimispeli/Tyokykypolkuja.WebUI'
alias t-peli-infra='bash ~/.config/tmux/tmux-sessionizer.sh ~/Code/Work/Keva/Tyokykypolkuja-oppimispeli/Tyokykypolkuja.Infra'
alias t-www='bash ~/.config/tmux/tmux-sessionizer.sh ~/Code/Personal/pasibergman-fi'
alias t='bash ~/.config/tmux/tmux-sessionizer.sh'
alias tmux-s='bash ~/.config/tmux/tmux-sessionizer.sh'
alias fzf-tmux='bash ~/.config/tmux/fzf-tmux.sh'
